//! Embeds every translation under `locales/` into the binary.
//!
//! Each folder `locales/<code>/` is one language, and every `.ftl` file in it
//! is part of that language. The folders are discovered here rather than
//! listed in Rust, so adding a language means adding a folder — nothing else.
//! Embedding (rather than reading at runtime) is what lets the same build run
//! in a browser, where there is no file system to read from.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

fn main() {
    let locales = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("locales");
    // A directory here makes cargo rescan everything under it.
    println!("cargo:rerun-if-changed={}", locales.display());

    let mut languages: Vec<_> = fs::read_dir(&locales)
        .expect("a `locales/` folder next to Cargo.toml")
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.is_dir())
        .collect();
    languages.sort();

    let mut out = String::from(
        "/// `(language code, [(file name, contents)])`, generated by `build.rs`.\n\
         pub(crate) const LOCALES: &[(&str, &[(&str, &str)])] = &[\n",
    );
    for language in languages {
        let code = language.file_name().unwrap().to_str().unwrap();
        let mut files: Vec<_> = fs::read_dir(&language)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .filter(|path| path.extension().is_some_and(|ext| ext == "ftl"))
            .collect();
        files.sort();

        writeln!(out, "    ({code:?}, &[").unwrap();
        for file in files {
            let name = file.file_name().unwrap().to_str().unwrap();
            writeln!(
                out,
                "        ({name:?}, include_str!({:?})),",
                file.display()
            )
            .unwrap();
        }
        writeln!(out, "    ]),").unwrap();
    }
    out.push_str("];\n");

    fs::write(
        Path::new(&env::var("OUT_DIR").unwrap()).join("locales.rs"),
        out,
    )
    .unwrap();
}
